# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Install Kythe, extract Kzips, and upload to GCP to enable semantic indexing on
# https://cs.opensource.google/opentitan

name: kythe

on:
  # For debugging, it's useful to have the action run whenever the PR is
  # modified. This can be accomplished by setting a bare `pull_request:` with no
  # items specified.
  #
  # Under normal circumstances, the action should only run when PRs are merged,
  # and possibly less frequently.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges-1
  #
  # TODO(dmcardle) Run only when PRs are merged.
  pull_request:

jobs:
  build_and_upload_kzips:
    name: 'Build and upload kzips for Kythe/Codesearch'

    runs-on: ubuntu-20.04
    # TODO(dmcardle) Delete environment line before merging. The "Kythe"
    # environment is specific to the dmcardle/opentitan GitHub repo.
    environment: Kythe
    steps:
      - name: Report glibc version
        run: |
          ldd --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: |
          ci/install-package-dependencies.sh \
            --verilator-version 4.210 \
            --openocd-version 0.11.0 \
            --verible-version v0.0-2135-gb534c1fe \
            --rust-version 1.60.0

      - name: Generate and Merge Kzips
        run: |
          set -ex

          . util/build_consts.sh
          MERGED_KZIP_PATH="${GITHUB_SHA}_${GITHUB_RUN_ID}.kzip"
          echo "MERGED_KZIP_PATH=$MERGED_KZIP_PATH" >> $GITHUB_ENV

          ci/scripts/generate_kythe_kzips.sh "${MERGED_KZIP_PATH}"

      - name: Authenticate to GCP
        # See https://github.com/google-github-actions/auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_KYTHE_UPLOADER }}'

      - name: Upload Merged Kzip to GCS Bucket
        # See https://github.com/google-github-actions/upload-cloud-storage
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '${{ env.MERGED_KZIP_PATH }}'
          destination: 'opentitan-kythe'
